### ISSUE TITLE
Add ApiGateway Datadog - AWS Integration

### ISSUE THREAD

**Issue by adinovriansyah** [traveloka/terraform-aws-common-iam-roles#16]
When I see, in data.aws_iam_policy_document.datadog_privilege_doc policy, there is no ApiGateway AWS - Datadog integration. Should we add it?

**Comment by rafikurnia** [comment]
Currently we have a discussion on #17 whether we should keep updating this module or not. You can join to the discussion and provide your feedback :smile:
